/**
 * GitHub Selectors — generated by MCP Accessibility Bridge
 *
 * These selectors were produced by Claude reading the live GitHub accessibility
 * tree via the MCP Accessibility Bridge server. Each selector is the
 * "recommended" output from get_interactive_elements / get_element_properties.
 *
 * Generation prompt used:
 *   "Navigate to github.com and list all interactive elements with Playwright selectors"
 *   "Navigate to github.com/login and list all interactive elements with Playwright selectors"
 *
 * All selectors use Priority 1 (data-testid) or Priority 3 (ARIA role + name)
 * for maximum stability across GitHub UI updates.
 */

// ── Home page ────────────────────────────────────────────────────────────────
export const Home = {
  // Navigation header
  signInLink:     () => page.getByRole('link',   { name: 'Sign in' }),
  signUpLink:     () => page.getByRole('link',   { name: 'Sign up' }),
  searchInput:    () => page.getByRole('combobox', { name: 'Search or jump to...' }),

  // Hero section
  heroHeading:    () => page.getByRole('heading', { name: /where the world builds software/i }),
  emailInput:     () => page.getByRole('textbox', { name: 'Email address' }),
  signUpButton:   () => page.getByRole('button',  { name: 'Sign up for GitHub' }),
} as const;

// ── Login page (/login) ──────────────────────────────────────────────────────
export const Login = {
  heading:          () => page.getByRole('heading',  { name: 'Sign in to GitHub' }),
  usernameInput:    () => page.getByRole('textbox',  { name: 'Username or email address' }),
  passwordInput:    () => page.getByRole('textbox',  { name: 'Password' }),
  signInButton:     () => page.getByRole('button',   { name: 'Sign in', exact: true }),
  forgotPassword:   () => page.getByRole('link',     { name: 'Forgot password?' }),
  createAccount:    () => page.getByRole('link',     { name: 'Create an account' }),
} as const;

// ── Search results page ──────────────────────────────────────────────────────
export const Search = {
  searchInput:      () => page.getByRole('combobox', { name: 'Search GitHub' }),
  repositoriesTab:  () => page.getByRole('tab',      { name: /repositories/i }),
  codeTab:          () => page.getByRole('tab',      { name: /code/i }),
  issuesTab:        () => page.getByRole('tab',      { name: /issues/i }),
  resultsRegion:    () => page.getByRole('region',   { name: /search results/i }),
} as const;

// ── Repository page ──────────────────────────────────────────────────────────
export const Repository = {
  codeTab:          () => page.getByRole('tab',      { name: 'Code' }),
  issuesTab:        () => page.getByRole('tab',      { name: 'Issues' }),
  prsTab:           () => page.getByRole('tab',      { name: 'Pull requests' }),
  starButton:       () => page.getByRole('button',   { name: /star/i }),
  forkButton:       () => page.getByRole('button',   { name: /fork/i }),
  cloneButton:      () => page.getByRole('button',   { name: 'Code' }),
  fileTree:         () => page.getByRole('grid',     { name: /files/i }),
} as const;
