/**
 * GitHub Home Page Tests
 *
 * Selectors generated by MCP Accessibility Bridge.
 *
 * Claude prompt used to generate these:
 *   > "Navigate to https://github.com and show me the accessibility tree.
 *      List all interactive elements with Playwright selectors.
 *      Write a test file that verifies the main home page elements."
 *
 * Every locator below came directly from get_interactive_elements output —
 * zero time spent in DevTools.
 */

import { test, expect } from '@playwright/test';

test.describe('GitHub Home Page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('page has correct title', async ({ page }) => {
    await expect(page).toHaveTitle(/GitHub/);
  });

  test('navigation: Sign in and Sign up links are visible', async ({ page }) => {
    // Selectors from: get_interactive_elements → role=link
    await expect(page.getByRole('link', { name: 'Sign in' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Sign up' })).toBeVisible();
  });

  test('hero section: heading and email signup are present', async ({ page }) => {
    // Selectors from: get_accessibility_tree → role=heading
    await expect(
      page.getByRole('heading', { name: /where the world builds software/i })
    ).toBeVisible();

    // Selectors from: get_interactive_elements → role=textbox
    await expect(
      page.getByRole('textbox', { name: 'Email address' })
    ).toBeVisible();
  });

  test('search bar is accessible via keyboard', async ({ page }) => {
    // Selector from: query_accessibility_tree → role=combobox
    const search = page.getByRole('combobox', { name: 'Search or jump to...' });

    // Verify it's reachable by keyboard
    await search.focus();
    await expect(search).toBeFocused();
  });

  test('email signup CTA can be interacted with', async ({ page }) => {
    const emailInput = page.getByRole('textbox', { name: 'Email address' });
    const signUpButton = page.getByRole('button', { name: 'Sign up for GitHub' });

    await emailInput.fill('test@example.com');
    await expect(emailInput).toHaveValue('test@example.com');
    await expect(signUpButton).toBeEnabled();
  });

  test('accessibility: main landmark regions exist', async ({ page }) => {
    // Accessibility audit: key ARIA landmark regions
    // Found via: get_accessibility_tree → role=banner, main, contentinfo
    await expect(page.getByRole('banner')).toBeVisible();     // header
    await expect(page.getByRole('main')).toBeVisible();       // main content
    await expect(page.getByRole('contentinfo')).toBeVisible(); // footer
  });

  test('accessibility: page has a single h1', async ({ page }) => {
    const h1s = page.getByRole('heading', { level: 1 });
    await expect(h1s).toHaveCount(1);
  });
});
