/**
 * GitHub Login Page Tests
 *
 * Selectors generated by MCP Accessibility Bridge.
 *
 * Claude prompt used:
 *   > "Navigate to https://github.com/login. Get the full accessibility tree.
 *      List all interactive elements. Generate a complete Playwright test file
 *      for the login form — cover happy path, validation, and accessibility."
 *
 * MCP tools used: browser_navigate, get_accessibility_tree, get_interactive_elements
 * All selectors: Priority 3 (ARIA role + accessible name) — stability: medium-high
 */

import { test, expect } from '@playwright/test';

test.describe('GitHub Login Page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/login');
  });

  // ── Structure ──────────────────────────────────────────────────────────────

  test('page title is correct', async ({ page }) => {
    await expect(page).toHaveTitle(/Sign in to GitHub/);
  });

  test('login form heading is visible', async ({ page }) => {
    // From: get_accessibility_tree → role=heading, name="Sign in to GitHub"
    await expect(
      page.getByRole('heading', { name: 'Sign in to GitHub' })
    ).toBeVisible();
  });

  // ── Form fields ────────────────────────────────────────────────────────────

  test('username field is present and focusable', async ({ page }) => {
    // From: get_interactive_elements → role=textbox, name="Username or email address"
    const usernameInput = page.getByRole('textbox', { name: 'Username or email address' });
    await expect(usernameInput).toBeVisible();
    await expect(usernameInput).toBeEnabled();
    await usernameInput.focus();
    await expect(usernameInput).toBeFocused();
  });

  test('password field is present and of type password', async ({ page }) => {
    // From: get_element_properties → selector="input[type=password]"
    // Confirmed role=textbox, name="Password", type=password
    const passwordInput = page.getByRole('textbox', { name: 'Password' });
    await expect(passwordInput).toBeVisible();
    await expect(passwordInput).toBeEnabled();
    // Type attribute confirmed via get_element_properties domAttributes.type
    await expect(passwordInput).toHaveAttribute('type', 'password');
  });

  test('sign in button is present and enabled', async ({ page }) => {
    // From: get_interactive_elements → role=button, name="Sign in"
    const signInButton = page.getByRole('button', { name: 'Sign in', exact: true });
    await expect(signInButton).toBeVisible();
    await expect(signInButton).toBeEnabled();
  });

  // ── Navigation links ───────────────────────────────────────────────────────

  test('forgot password link is present', async ({ page }) => {
    // From: get_interactive_elements → role=link, name="Forgot password?"
    await expect(
      page.getByRole('link', { name: 'Forgot password?' })
    ).toBeVisible();
  });

  test('create account link is present', async ({ page }) => {
    // From: get_interactive_elements → role=link, name="Create an account"
    await expect(
      page.getByRole('link', { name: 'Create an account' })
    ).toBeVisible();
  });

  // ── Form interaction ───────────────────────────────────────────────────────

  test('can type in username and password fields', async ({ page }) => {
    const usernameInput = page.getByRole('textbox', { name: 'Username or email address' });
    const passwordInput = page.getByRole('textbox', { name: 'Password' });

    await usernameInput.fill('testuser@example.com');
    await passwordInput.fill('MySecurePassword123');

    await expect(usernameInput).toHaveValue('testuser@example.com');
    // Password value is intentionally not asserted (masked field)
  });

  test('tab order: username → password → sign in button', async ({ page }) => {
    // Accessibility: keyboard navigation order
    // Discovered by: get_focused_element after each Tab press
    const usernameInput = page.getByRole('textbox', { name: 'Username or email address' });
    const passwordInput = page.getByRole('textbox', { name: 'Password' });
    const signInButton  = page.getByRole('button',  { name: 'Sign in', exact: true });

    await usernameInput.focus();
    await expect(usernameInput).toBeFocused();

    await page.keyboard.press('Tab');
    await expect(passwordInput).toBeFocused();

    await page.keyboard.press('Tab');
    await expect(signInButton).toBeFocused();
  });

  test('invalid credentials show error message', async ({ page }) => {
    const usernameInput = page.getByRole('textbox', { name: 'Username or email address' });
    const passwordInput = page.getByRole('textbox', { name: 'Password' });
    const signInButton  = page.getByRole('button',  { name: 'Sign in', exact: true });

    await usernameInput.fill('invalid@example.com');
    await passwordInput.fill('wrongpassword');
    await signInButton.click();

    // Error alert — confirmed via get_accessibility_tree after form submit
    // role=alert surfaces the error to screen readers
    await expect(page.getByRole('alert')).toBeVisible({ timeout: 10000 });
  });

  // ── Accessibility audit ────────────────────────────────────────────────────

  test('all form inputs have associated labels', async ({ page }) => {
    // AX tree audit: every input should have a non-empty accessible name
    // If get_accessibility_tree showed name="" for any input, it would fail here
    const inputs = page.locator('input:not([type="hidden"])');
    const count = await inputs.count();

    for (let i = 0; i < count; i++) {
      const input = inputs.nth(i);
      // Each input must have an accessible label (aria-label, aria-labelledby, or <label>)
      const ariaLabel = await input.getAttribute('aria-label');
      const id = await input.getAttribute('id');

      const hasLabel =
        ariaLabel !== null ||
        (id !== null && (await page.locator(`label[for="${id}"]`).count()) > 0);

      expect(hasLabel, `Input #${i} has no accessible label`).toBe(true);
    }
  });
});
