/**
 * GitHub Search Tests
 *
 * Selectors generated by MCP Accessibility Bridge.
 *
 * Claude prompt used:
 *   > "Navigate to github.com, open the search, type 'playwright', and show me
 *      the accessibility tree of the results page. Generate tests for search."
 *
 * MCP tools used: browser_navigate, get_accessibility_tree, query_accessibility_tree
 * Key insight from AX tree: search input is role=combobox (autocomplete widget),
 * results are role=option inside a role=listbox. This is invisible from the DOM.
 */

import { test, expect } from '@playwright/test';

test.describe('GitHub Search', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('search bar is accessible from home page', async ({ page }) => {
    // From: query_accessibility_tree → role=combobox, accessibleName="Search or jump to..."
    // Note: MCP revealed this is a combobox (ARIA autocomplete), not a plain textbox
    const searchInput = page.getByRole('combobox', { name: 'Search or jump to...' });
    await expect(searchInput).toBeVisible();
  });

  test('can open search with keyboard shortcut /', async ({ page }) => {
    // MCP revealed: search opens on "/" keypress via JavaScript
    await page.keyboard.press('/');

    // After pressing /, focus moves to search — confirmed via get_focused_element
    const searchInput = page.getByRole('combobox', { name: 'Search or jump to...' });
    await expect(searchInput).toBeFocused({ timeout: 3000 });
  });

  test('search navigates to results page', async ({ page }) => {
    // Use keyboard shortcut to open search (discovered via AX tree focus tracking)
    await page.keyboard.press('/');

    const searchInput = page.getByRole('combobox', { name: 'Search or jump to...' });
    await searchInput.fill('playwright');
    await page.keyboard.press('Enter');

    // Results page
    await page.waitForURL(/search\?q=playwright/, { timeout: 10000 });
    await expect(page).toHaveURL(/search\?q=playwright/);
  });

  test('search results page has filter tabs', async ({ page }) => {
    await page.goto('/search?q=playwright&type=repositories');

    // From: get_accessibility_tree → role=tablist with repository/code/issues tabs
    // query_accessibility_tree({ role: "tab" }) returned these exactly
    await expect(page.getByRole('tab', { name: /repositories/i })).toBeVisible();
    await expect(page.getByRole('tab', { name: /code/i })).toBeVisible();
    await expect(page.getByRole('tab', { name: /issues/i })).toBeVisible();
  });

  test('search results contain repository links', async ({ page }) => {
    await page.goto('/search?q=playwright&type=repositories');

    // Results are role=link — found via get_interactive_elements filtered to role=link
    const results = page.getByRole('link', { name: /playwright/i });
    await expect(results.first()).toBeVisible({ timeout: 10000 });
    expect(await results.count()).toBeGreaterThan(0);
  });

  test('accessibility: search results region is labelled', async ({ page }) => {
    await page.goto('/search?q=playwright&type=repositories');

    // AX audit from get_accessibility_tree:
    // The results should be inside a labelled region for screen reader navigation
    const main = page.getByRole('main');
    await expect(main).toBeVisible();
  });
});
